import {CustomerDefaultDeliveryType} from "./customer-default-delivery-types.ts";
import {CustomerType} from "./customer-type.ts";
import {CustomerVatType} from "./customer-vat-type.ts";

export interface ICustomer {
    '@url': string;
    Active: boolean;
    Address1: string;
    Address2: string;
    City: string;
    Comments: string;
    CostCenter: string;
    Country: string;
    CountryCode: string;
    Currency: string;
    CustomerNumber: string;
    DefaultDeliveryTypes: {
        Invoice: CustomerDefaultDeliveryType;
        Offer: CustomerDefaultDeliveryType;
        Order: CustomerDefaultDeliveryType;
    };
    DefaultTemplates: {
        CashInvoice: string;
        Invoice: string;
        Offer: string;
        Order: string;
    };
    DeliveryAddress1: string;
    DeliveryAddress2: string;
    DeliveryCity: string;
    DeliveryCountry: string;
    DeliveryCountryCode: string;
    DeliveryFax: string;
    DeliveryName: string;
    DeliveryPhone1: string;
    DeliveryPhone2: string;
    DeliveryZipCode: string;
    Email: string;
    EmailInvoice: string;
    EmailInvoiceBCC: string;
    EmailInvoiceCC: string;
    EmailOffer: string;
    EmailOfferBCC: string;
    EmailOfferCC: string;
    EmailOrder: string;
    EmailOrderBCC: string;
    EmailOrderCC: string;
    ExternalReference: string;
    Fax: string;
    GLN: string;
    GLNDelivery: string;
    InvoiceAdministrationFee: string;
    InvoiceDiscount: number;
    InvoiceFreight: string;
    InvoiceRemark: string;
    Name: string;
    OrganisationNumber: string;
    OurReference: string;
    Phone1: string;
    Phone2: string;
    PriceList: string;
    Project: string;
    SalesAccount: string;
    ShowPriceVATIncluded: boolean;
    TermsOfDelivery: string;
    TermsOfPayment: string;
    Type: CustomerType;
    VATNumber: string;
    VATType: CustomerVatType;
    VisitingAddress: string;
    VisitingCity: string;
    VisitingCountry: string;
    VisitingCountryCode: string;
    VisitingZipCode: string;
    WWW: string;
    WayOfDelivery: string;
    YourReference: string;
    ZipCode: string;
}
